PizzaShop/Models/ShoppingCartViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PizzaShop.Models
{
    public class ShoppingCartViewModel
    {
        public List<CartItem> CartPizzas { get; set; }
        public decimal CartTotalPrice { get; set; }
    }
}

PizzaShop/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PizzaShop.Models;
using System.Data;
using System.Data.Entity;
using System.Net;
using Microsoft.AspNet.Identity;
using System.Diagnostics;
using PizzaShop.Hubs;
using Microsoft.AspNet.SignalR;
using Newtonsoft.Json;

namespace PizzaShop.Controllers
{
    public class OrdersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // List all orders
        // GET: /Orders/Index
        [System.Web.Mvc.Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            ViewBag.CartTotalPrice = ShoppingCartController.GetCartTotalPrice();

            return View(db.Orders.Include(o => o.OrderLines).OrderByDescending(o => o.OrderDate).ToList());
        }

        // GET: /Orders/Detail/5
        [System.Web.Mvc.Authorize(Roles = "admin")]
        public ActionResult Detail(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var order = db.Orders
                .Include(o => o.OrderLines)
                .Include("OrderLines.Pizza.Toppings")
                .Include("OrderLines.CustomPizzaToppings.Topping")
                .Where(c => c.ID == id).First();

            //var order = db.Orders.Include(o => o.OrderLines).Where(c => c.ID == id);

            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // GET: Enter order details
        public ActionResult Order()
        {
            var cart = (List<CartItem>)Session["cart"];

            ViewBag.Cart = cart;

            // Return to cart if it doesn't exist or there are no CartItems.
            if(cart == null)
            {
                return RedirectToAction("Index", "ShoppingCart");
            } else if(cart.Count < 1)
            {
                return RedirectToAction("Index", "ShoppingCart");
            }

            var user = db.Users.Find(User.Identity.GetUserId());

            ViewBag.CartTotalPrice = ShoppingCartController.GetCartTotalPrice();

            if (user != null)
            {
                Order order = new Order();
                order.DeliveryAddress = user.HomeAddress;
                order.DeliveryCity = user.HomeCity;
                order.DeliveryPostCode = user.HomePostCode;
                order.PhoneNumber = user.PhoneNumber;
                order.Email = user.Email;
                order.Client = user;

                return View(order);
            }

            return View();
        }

        // POST: Orders/Order
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Order([Bind(Include = "Id,DeliveryAddress,DeliveryPostCode,DeliveryCity,PhoneNumber,Email")] Order order)
        {
            order.OrderDate = DateTime.Now;

            if (ModelState.IsValid)
            {
                var cart = (List<CartItem>)Session["cart"];

                decimal totalPrice = 0m;

                foreach (var cartItem in cart)
                {
                    OrderLine orderLine = new OrderLine();
                    //orderLine.Pizza = cartItem.Pizza;
                    orderLine.PizzaID = cartItem.Pizza.ID;
                    orderLine.Order = order;
                    orderLine.PriceEur = cartItem.GetActualPrice();

                    totalPrice += cartItem.GetActualPrice();

                    var extraToppings = cartItem.ExtraToppings;

                    if (extraToppings != null)
                    {
                        foreach (var pizzaTopping in cartItem.ExtraToppings)
                        {
                            CustomPizzaTopping customPizzaTopping = new CustomPizzaTopping();
                            customPizzaTopping.OrderLine = orderLine;
                            //customPizzaTopping.Topping = pizzaTopping;
                            customPizzaTopping.ToppingID = pizzaTopping.ID;
                            orderLine.addCustomPizzaTopping(customPizzaTopping);
                        }
                    }

                    order.addOrderLine(orderLine);
                }

                order.PriceEur = totalPrice;

                db.Orders.Add(order);
                db.SaveChanges();

                // Parse the new Order into JSON.
                // Ignore self-referencing fields to avoid Exception (e.g. the Order-property).
                string json = JsonConvert.SerializeObject(order, Formatting.Indented,
                    new JsonSerializerSettings
                    {
                        ReferenceLoopHandling = ReferenceLoopHandling.Ignore
                    }
                );

                // Inform web socket clients of the new order
                var context = GlobalHost.ConnectionManager.GetHubContext<OrderHub>();
                context.Clients.All.addNewOrder(json);

                // Finally clear the shopping cart
                Session.Contents.Remove("cart");

                return RedirectToAction("Index", "Home");
            }

            return View(order);
        }
    }
}

PizzaShop/Controllers/ShoppingCartController.cs
using PizzaShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace PizzaShop.Controllers
{
    public class ShoppingCartController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();

        // GET: ShoppingCart
        public ActionResult Index()
        {
            // Init cart if it doesn't already exist
            List<CartItem> cart = (List<CartItem>)Session["cart"] ?? new List<CartItem>();

            decimal totalPrice = Utils.CountCartTotalPrice(cart);

            // For displaying the current cart price on load
            ViewBag.CartTotalPrice = totalPrice;

            var viewModel = new ShoppingCartViewModel
            {
                CartPizzas = cart,
                CartTotalPrice = totalPrice
            };

            return View(viewModel);
        }

        //
        // GET: /Store/AddToCart/5
        [HttpPost]
        public ActionResult AddToCart(int id)
        {
            // Retrieve the Pizza to add from the database
            var addedPizza = db.Pizzas
                .Include(p => p.Toppings)
                .Single(p => p.ID == id);
            
            // Init cart if it doesn't already exist
            List<CartItem> cart = (List<CartItem>)Session["cart"] ?? new List<CartItem>();

            // Add to shopping cart
            cart.Add(new CartItem {
                ID = long.Parse(addedPizza.ID.ToString() +
                    Utils.UnixTimeNow().ToString()),
                Pizza = addedPizza
            });

            // Update session
            Session["cart"] = cart;

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(addedPizza.Name) +
                    " has been added to your cart.",
                CartTotalPrice = Utils.CountCartTotalPrice(cart),
                ItemCount = cart.Count()
            };
            return Json(results);
        }

        //
        // POST: /ShoppingCart/AddCustomToCart
        [HttpPost]
        public ActionResult AddCustomToCart(int id, int[] toppingIds)
        {
            // Init cart if it doesn't already exist
            List<CartItem> cart = (List<CartItem>)Session["cart"] ?? new List<CartItem>();

            Pizza selectedBasePizza = db.Pizzas
                .Include(p => p.Toppings)
                .FirstOrDefault(p => p.ID == id);

            // The toppings won't replace the Pizza's toppings,
            // but will instead be included in the CartItem.ExtraToppings List.
            //
            // NOTE: Not enough to just find every Topping in DB,
            // because there might be multiple instances of the same Topping
            // that need to be added here.
            List<Topping> extraToppings = toppingIds
                .Select(tId => db.Toppings.FirstOrDefault(d => d.ID == tId))
                .Where(res => res != null)
                .ToList();

            // Create a CartItem with any selected extra Toppings
            // and the base Pizza
            CartItem item = new CartItem
            {
                ID = long.Parse(selectedBasePizza.ID.ToString() +
                    Utils.UnixTimeNow().ToString()),
                Pizza = selectedBasePizza,
                ExtraToppings = extraToppings
            };

            // Add to shopping cart
            cart.Add(item);

            // Update session
            Session["cart"] = cart;

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode("") +
                    " has been added to your cart.",
                CartTotalPrice = Utils.CountCartTotalPrice(cart),
                ItemCount = cart.Count()
            };
            return Json(results);
        }

        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(long id)
        {
            // Remove the item from the cart
            var cart = (List<CartItem>)Session["cart"];

            CartItem itemToRemove = cart.SingleOrDefault(item => item.ID == id);

            string pizzaName = "";

            if (itemToRemove != null)
            {
                pizzaName = itemToRemove.Pizza.Name;
                cart.Remove(itemToRemove);
            }

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = "One (1) " + Server.HtmlEncode(pizzaName) +
                    " has been removed from your shopping cart.",
                CartTotalPrice = Utils.CountCartTotalPrice(cart),
                ItemCount = cart.Count(),
                DeleteId = id
            };
            return Json(results);
        }

        // Public getter for current total price of cart items
        public static decimal GetCartTotalPrice()
        {
            List<CartItem> cart = (List<CartItem>)System.Web.HttpContext.Current.Session["cart"];
            return Utils.CountCartTotalPrice(cart);
        }
    }
}

PizzaShop/Views/ShoppingCart/Index.cshtml
@using PizzaShop.Models
@model ShoppingCartViewModel

@{ 
    ViewBag.Title = "Shopping Cart";
}

<script type="text/javascript">
    $(function () {
        $(".remove-item-link").click(function (e) {
            // Get the id from the link
            var pizzaToDelete = $(this).attr("data-id");
            if (pizzaToDelete != '') {
                // Perform the ajax post
                $.post(
                    "/ShoppingCart/RemoveFromCart",
                    { "id": pizzaToDelete },
                    function (data) {
                        var price = String(data.CartTotalPrice).replace(".", ",");
                        $('#row-' + data.DeleteId).fadeOut('fast');
                        $('#cart-total').text(price);
                        $("#cart-main-btn").text("Shopping cart (" + price + " €)");
                    }
                );
            }
        });
    });
</script>

<h3>Your shopping cart</h3>

@{

    if (Model.CartPizzas.Count() > 0)
    {
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Order Summary</h3>
            </div>
            <div class="panel-body">
                <table class="table table-striped table-hover ">
                    <thead>
                        <tr>
                            <th>Pizza</th>
                            <th>Toppings</th>
                            <th>Extra toppings</th>
                            <th>Price</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>

                    </tbody>
                        @foreach (var item in Model.CartPizzas)
                        {
                            <tr id="row-@item.ID">
                                <td>@item.Pizza.Name</td>
                                <td>
                                    @{ int i = 0; }
                                    @foreach (Topping t in item?.Pizza?.Toppings ?? new List<Topping>())
                                    {
                                        if (i + 1 < item.Pizza.Toppings.Count())
                                        {
                                            @: @t.Name, 
                                        } else
                                        {
                                            @: @t.Name
                                        }
                                        i++;
                                    }
                                </td>
                                <td>
                                    @{ int j = 0; }
                                    @foreach (Topping t in item?.ExtraToppings ?? new List<Topping>())
                                    {
                                        if (j + 1 < item.ExtraToppings.Count())
                                        {
                                            @: @t.Name,
                                        }
                                        else
                                        {
                                            @: @t.Name
                                        }
                                        j++;
                                    }
                                </td>
                                <td>@item.GetActualPrice().ToString().Replace(".", ",") &euro;</td>
                                <td>
                                    <a href="#" class="remove-item-link" data-id="@item.ID">Remove from cart</a>
                                </td>
                            </tr>
                        }
                    <tfoot>
                        <tr class="active">
                            <td><strong>Total</strong></td>
                            <td></td>
                            <td></td>
                            <td>
                                <strong id="cart-total">@Model.CartTotalPrice.ToString().Replace(".", ",")</strong> &euro;
                            </td>
                            <td></td>
                        </tr>
                    </tfoot>
                </table>
                <button type="button" class="btn btn-success btn-sm" onclick="location.href='@Url.Action("Order", "Orders")'">
                    Check Out &raquo;
                </button>
            </div>
        </div>
    }
    else
    {
        <div>
            <p>
                You haven't added any pizzas to your shopping cart. Go and pick some pizzas you like!
            </p>
        </div>
    }
}